### ISSUE TITLE
[Feature Request] Extend hold right button + klick left to toggle between a set zoom level and default

### ISSUE THREAD

**Issue by derdershat** [simper66/MouseZoomer#1]
Hi simper66,

used the old but great addon [MouseZoom from MrPradox](https://addons.mozilla.org/de/firefox/addon/mousezoom/) in Firefox < 56 for years.
Yepp and Firefox changed to WebExtentions.. we all know this ...

With your addon I found a replacement and I am very happy and thankful to have a feature back without I do not want to use a browser anymore. 

Could you think about adding another feature? 

to hold the right mouse button and click the left mouse button to jump to a certain zoom value or reset to 100% zoom --- par ex a toggle between 100% and 130% by holding right mouse and click left 130% and click again left back to 100%(default) 

thank you for your MouseZoomer addon for Firefox.

greats
derdershat

**Comment by simper66** [comment]
done...new "reset to X%" for L+R and for R+L

**Comment by fwosar** [comment]
That's unfortunately not what the user asked for. They asked for a way to have the same mouse combination toggle between two different zoom levels. I know, because I was going to ask for the same.

So for example: Pressing the Right Click + Left Click combination, would set the zoom to 150% and when clicking the same combination again would switch it back to 100%. 

Your solution however, allows to specify two different mouse click combinations to set the zoom level for each of the combinations. However, most Mousezoom users switching from Chrome or who used to use the old Firefox extension, will have a hard time switching as the toggling is so deeply ingrained into muscle memory. I know it is for me.

So would you maybe consider changing it? :)
